/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_main/config/camera_info.yaml
    exposure_time: 2500
    gain: 8.0

/rm_serial_driver:
  ros__parameters:
    timestamp_offset: 0.001
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
    is_hero: false

/detect_node:
  ros__parameters:
    binary_thres: 80
    compensation_1: 1.0 
    compensation_2: 1.0
    compensation_3: 1.0
    compensation_4: 1.0 
    mode: 0
    dart_number: 0
    #debug
    debug: true












