/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_main/config/camera_info.yaml
    exposure_time: 3000
    gain: 8.0

/rm_serial_driver:
  ros__parameters:
    timestamp_offset: 0.001
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
    is_hero: false

/detector_node:
#左减右加
# 中上 中 左上 中
# 中  中  中   中
# 右 右 中 
  ros__parameters:
    binary_thres: 80
    compensation_1: 10 # 30
    compensation_2: 10 # 30
    compensation_3: 10 # 40
    compensation_4: 10 # 40
    mode: 0
    dart_number: 0
    #debug
    debug: true












